### ISSUE TITLE
AVX2 instructions stop VS 2017 Debug build from running on AVX-only processors

### ISSUE THREAD

**Issue by richforster** [GameTechDev/OcclusionCulling#1]
MaskedOcclusionCullingPrivate::SetResolution() uses the intrinsic _mm256_set1_ps() which in the Debug|x64 build in Visual Studio 2017 (cl.exe version 19.10.25019) compiles to the register to register version of vbroadcastss which is an AVX2 instruction (according to https://en.wikipedia.org/wiki/Advanced_Vector_Extensions). Locally adding a lambda to replace this with the memory to register version appears to fix this:

		auto _mm256_set1_ps = [](float f)
		{
			return _mm256_broadcast_ss(&f);
		};

This doesn't appear required for the Release|x64 build which heavily flattens SetResolution().

Thanks for the great sample code!

**Comment by fstrugar** [comment]
Good catch, and even better workaround, thanks! We'll look it and see to file the compiler bug as it looks like an issue with VS2017 as you say.

Btw, just for your info - this repository has not been updated for a while and the latest Masked Occlusion Culling code is actually here: https://github.com/GameTechDev/MaskedOcclusionCulling with a number of fixes and upgrades. We should figure out how to keep them in sync in the future.

Many thanks!!

**Comment by fstrugar** [comment]
One update on this: the up-to-date codebase at https://github.com/GameTechDev/MaskedOcclusionCulling will not call the offending instruction in SSE2 and SSE4.1 codepaths, only in AVX2 and above, and the [DetectCPUFeatures](https://github.com/GameTechDev/MaskedOcclusionCulling/blob/bab559d89e090711169694291165b0dd7354085e/MaskedOcclusionCulling.cpp#L35) should give correct max supported instruction set (SSE4.1) for up-to-AVX supporting CPUs.
Apologies for not keeping this codebase up to date with the main MOC one, I'll leave the bug open until I sort that out.

**Comment by richforster** [comment]
Thanks for taking the time to followup. I read the MOC paper when it came out but have forgotten about it since - thanks for the reminder! I'm not 100% sure it's not a VS bug since it still generates the AVX2 opcode with the AVX only switch - I'm just glad my hacky workaround worked!

**Comment by fstrugar** [comment]
You're welcome. Oh I did not mean to imply that it's not a VS bug - _mm256_set1_ps shouldn't emit AVX2 opcode with AVX only, you're right. It's just that the new MOC codebase doesn't even use _mm256_set1_ps for 'below AVX2' codepaths so it should work regardless :)
I'm looking into updating the sample with latest MOC code.
