### ISSUE TITLE
AVG frame rate wrong

### ISSUE THREAD

**Issue by ramassin** [GameTechDev/OcclusionCulling#2]
This line should read like below.
https://github.com/GameTechDev/OcclusionCulling/blob/cab133e1d44392997fdd3db13354369070511a13/CPUT/CPUTGuiControllerDX11.cpp#L471

```
	float total = 0.0f;
	for(int i = 0; i < AVG_FRAMES; i++)
	{
		total += mFPSAvg[i];
	}
```
Also, consider adding a \t in the output string to avoid the FPS counter jumping around.

`swprintf_s(&wcstring[0], CPUT_MAX_STRING_LENGTH, _L("FPS:%.1f \t(AVG:%.1f)"), fps, total);`

**Comment by fstrugar** [comment]
Many thanks - looks like the avg fps was fixed in one of the merged commits and I've just added the tab too!
